# Generated by Django 5.2 on 2025-04-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_empleados/')),
                ('contrato', models.FileField(blank=True, null=True, upload_to='contratos_empleados/')),
                ('numero_interno', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('documento_identidad', models.IntegerField(null=True)),
                ('domicilio', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.IntegerField(null=True)),
                ('EPS', models.CharField(max_length=100)),
                ('estado_civil', models.CharField(max_length=20)),
                ('dependientes_economicos', models.PositiveIntegerField(default=0)),
                ('cargo', models.CharField(max_length=100)),
                ('tipo_contrato', models.CharField(choices=[('Contrato a Término Fijo', 'Contrato a Término Fijo'), ('Contrato a término indefinido', 'Contrato a término indefinido'), ('Contrato de Obra o labor', 'Contrato de Obra o labor'), ('Contrato civil por prestación de servicios', 'Contrato civil por prestación de servicios'), ('Contrato de aprendizaje', 'Contrato de aprendizaje'), ('Contrato ocasional, accidental o transitorio de trabajo', 'Contrato ocasional, accidental o transitorio de trabajo')], max_length=100)),
                ('talla_ropa', models.CharField(max_length=10)),
                ('talla_calzado', models.IntegerField(null=True)),
                ('formacion_reglada', models.CharField(max_length=255)),
                ('formacion_complementaria', models.CharField(max_length=255)),
                ('institucion_graduacion', models.CharField(max_length=255)),
                ('experiencias_previas', models.TextField(blank=True)),
                ('relacion_empleado', models.CharField(max_length=100)),
                ('contacto_nombres', models.CharField(max_length=100)),
                ('contacto_apellidos', models.CharField(max_length=100)),
                ('contacto_fecha_nacimiento', models.DateField()),
                ('contacto_carnet_identidad', models.IntegerField()),
                ('contacto_domicilio', models.CharField(max_length=255)),
                ('contacto_telefono', models.IntegerField()),
                ('contacto_correo', models.EmailField(max_length=254)),
                ('banco', models.CharField(max_length=100)),
                ('tipo_cuenta', models.CharField(choices=[('Ahorros', 'Ahorros'), ('Corriente', 'Corriente')], max_length=20)),
                ('numero_cuenta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=100, unique=True, verbose_name='Identificacion')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('celular', models.CharField(max_length=15, unique=True)),
                ('genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=10)),
                ('cargo', models.CharField(choices=[('Administrativo', 'Administrativo'), ('Contador', 'Contador'), ('Recursos humanos', 'Recursos humanos')], default='', max_length=50)),
                ('imagen', models.ImageField(blank=True, max_length=200, null=True, upload_to='perfil/', verbose_name='Imagen de perfil')),
                ('usuario_activo', models.BooleanField(default=True)),
                ('usuario_administrador', models.BooleanField(default=False)),
                ('pais', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
