# Generated by Django 5.2 on 2025-05-24 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ejemplo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ejemplo',
        ),
    ]
