# Generated by Django 5.2.1 on 2025-05-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_ejemplo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=255)),
                ('area', models.CharField(max_length=255)),
                ('responsable', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('En ejecución', 'En ejecución'), ('Finalizado', 'Finalizado'), ('En planificación', 'En planificación')], max_length=50)),
                ('fecha_inicio', models.DateField()),
            ],
        ),
    ]
