# Generated by Django 5.2.1 on 2025-05-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_planformacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planformacion',
            name='estado',
            field=models.CharField(max_length=100),
        ),
    ]
